# Numpy library:-
------------------

In [1]:
import numpy as np
import sys

## 1. Creating ndarray:
------------------------
- from Python List
- using `numpy.zeros()` method.
- using `numpy.ones()` method.
- using `numpy.full()` method.
- using `numpy.identity()` method.
- using `numpy.random.rand()` method.
- using `numpy.random.randint()` method.

### 1D Array
--------------

In [2]:
a = np.array( [1,2,3] )
print(a, type(a))

[1 2 3] <class 'numpy.ndarray'>


In [3]:
print( sys.getsizeof(a) )

124


In [4]:
lst = [1,2,3,4]
arr = np.array(lst)

print( sys.getsizeof(lst), sys.getsizeof(arr) )

88 128


In [5]:
print( lst.__sizeof__(), arr.__sizeof__() )

72 128


### 2D Array:
--------------
**A 2D array is actually a matrix, thus each row must have same number of elements, else matrix cannot be formed.** <br>
For a 2D array to be formed, each inner list of the list of lists must contain same number of elements. <br>
Else, the array would be considered as a 1D array.

In [7]:
a = np.array( [[1,2,3],[10,20,30]] )
print(type(a), type(a[0]) )

<class 'numpy.ndarray'> <class 'numpy.ndarray'>


If we try to make a 2D array with a list of lists where each inner list has separate number of elements, then that will be considered as a 1D np array, where each element will be a list object(and not an np array of np arrays).

In [8]:
b = np.array( [[1,2,3], [10,20]] )
print( type(b), type(b[0]) )

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [10]:
b = np.array( [[1,2,3], [10,20]], dtype=object )
print( type(b), type(b[0]) )

<class 'numpy.ndarray'> <class 'list'>


In [9]:
c = np.array( [[1,2,3], "hello"] )
print( type(c), type(c[0]) )

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [11]:
c = np.array( [[1,2,3], "hello"], dtype=object )
print( type(c), type(c[0]) )

<class 'numpy.ndarray'> <class 'list'>


### To create homogenous data in array, numpy converts the narrow datatype values to broad datatype values:
- int to float
- int to string
- float to string
etc.
<br>
The rightmost datatype present in the below sequence, all will be converted to that datatype:<br>
int > float > string

In [14]:
# all the individual values are converted to string
a = np.array( [[1,2,3],[10,'20',30]] )
print(a, type(a), type(a[0]) )

[['1' '2' '3']
 ['10' '20' '30']] <class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [15]:
# all the individual values are converted to float
a = np.array( [[1,2,3.0],[10,20,30]] )
print(a, type(a), type(a[0]) )

[[ 1.  2.  3.]
 [10. 20. 30.]] <class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [16]:
# all the individual values are converted to string
a = np.array( [[1.0,2,3],[10,'20',30]] )
print(a, type(a), type(a[0]) )

[['1.0' '2' '3']
 ['10' '20' '30']] <class 'numpy.ndarray'> <class 'numpy.ndarray'>


## 2. Getting number of dimensions of array:
---------------------------------------------
The `ndim` member variable of the numpy array object contains the number of dimensions of the array.


In [2]:
a = np.array( [1,2,3] )
print( a.ndim )

1


In [3]:
b = np.array( [ [1,2,3], [10,20,30] ] )
print( b.ndim )

2


In [6]:
b = np.array( [[1,2,3], [10,20]], dtype=object )
print( b.ndim )

1


## 3. Getting ORDER / SHAPE of a numpy array:
----------------------------------------------
- The `shape` member variable of the numpy array object contains the shape/order of a numpy array, in the form of a tuple.
- The tuple contained in `shape` will have elements equal to number of dimensions of the numpy array, i.e., <br>
    len( nparray.shape ) == nparray.ndim
- Each number in the tuple is the number of elements that specific axis has.<br>
    Ex- array with shape (3,5) means:
  - It has 3(=element at index 0) rows(row is called 0 axis of a 2D nparray)
  - It has 5(=element at index 1) columns(column is called 1 axis of a 2D nparray)

In [7]:
a_1d_1 = np.array( [2,4] )
print( a_1d_1.shape )

(2,)


In [8]:
a_1d_2 = np.array( [4,6,8,9,10] )
print( a_1d_2.shape )

(5,)


In [10]:
# 2 rows(axis=0) and 3 columns(axis=1), thus 2 at index 0 and 3 at index 1 == (2,3)
a_2d_1 = np.array([ [2,4,6],[1,3,5] ])
print( a_2d_1.shape )

(2, 3)


In [15]:
# 3 rows(axis=0) and 5 columns(axis=1), thus 3 at index 0 and 5 at index 1 == (2,3)
list_3x5 = [
    [1,2,3,4,5],
    [10,20,30,40,50],
    [100,200,300,400,500]
]

a_2d_2 = np.array( list_3x5 )
print( a_2d_2.shape )

(3, 5)


In [17]:
# 2 elements at axis=0, in each such element 3 rows(axis=1) and 4 columns(axis=2), thus 2 at index=0, 3 at index 1 and 4 at index 2 == (2,3,4)
list_2x3x4 = [
    [
        [1,   2,  3,  4],
        [11, 22, 33, 44],
        [1,   2,  3,  4]
    ]
    ,
    [
        [10,   20,  30,  40],
        [100, 200, 300, 400],
        [101, 202, 303, 404]
    ]
]

a_3d_1 = np.array( list_2x3x4 )
print( a_3d_1.shape )

(2, 3, 4)


## 4. Checking datatype of Np Array elements:
-----------------------------------------------
- Using `dtype` member variable/ attribute of the numpy array objects, we can get to know the datatype of the array elements.
- The datatype of array elements are different than Python native datatypes. These datatypes are actually <u>*classes of the **numpy** module*</u>. Some of them are:<br>
    - numpy.int32
    - numpy.int64
- Datatype are according to data types and size occupied. Ex- np.int32 means each element is of integer type, that occupies 32 bits each.

In [19]:
a = np.array( [1,2,3,4] )
print( a.dtype )
print( type(a[0]) )

int32
<class 'numpy.int32'>


In [20]:
b = np.array( [1,2,3,4], dtype = np.int64 )
print( b.dtype )
print( type(b[0]) )

int64
<class 'numpy.int64'>


## 5. Changing datatypes of array elements, while array creation:-
-----------------------------------------------------------------------
To change datatype of an array, we need to pass a second parameter to the `np.array()` method, which is a keyword argument named `dtype`. It is passed as:
- `np.array( "data_in_array", dtype='int16' )` - Keyword argument passed is a string(of supported values).
- `np.array( "data_in_array", dtype=numpy.int16 )` - Keyword argument passed is a numpy module datatype classes.

Some datatypes of numpy module:-
- np.int8
- np.int16
- np.int32
- np.int64 <br><br>
- np.uint8
- np.uint16
- np.uint32
- np.uint64 <br><br>
- np.float32
- np.float64 <br><br>
- np.complex64
- np.complex128

In [21]:
a = np.array( [1,2,3], dtype='int16' )
print( a, a.dtype )

[1 2 3] int16


In [22]:
a = np.array( [1,2,3], dtype=np.int16 )
print( a, a.dtype )

[1 2 3] int16


## 6. Changing datatype of already created array:-
-----------------------------------------------------
- Using the `astype()` property / method / member function of numpy array object, datatype of array elements can be changed.
- As parameter of `astype()`, we need to pass the new datatype, as string or class name.
- `astype()` method **does not alter the datatype of the original array**. <u>It returns a new array, with the newly set datatype.</u>

In [24]:
a = np.array( [1,2,3] )
print("Initial datatype: ", a.dtype )
a = a.astype('int8')
print("Final datatype: ", a.dtype )

Initial datatype:  int32
Final datatype:  int8


In [25]:
a = np.array( [1,2,3] )
print("Initial datatype: ", a.dtype )
a = a.astype(np.float64)
print("Final datatype: ", a.dtype )

Initial datatype:  int32
Final datatype:  float64


## 7. Converting numpy array to Python LIST:-
-----------------------------------------------
- `tolist()` method of np array object returns the array by converting it into Python list.

In [26]:
a = np.array( [1,2,3] )
l = a.tolist()
print(l, type(l))

[1, 2, 3] <class 'list'>


## 8. Accessing and changing array elements:-
-----------------------------------------------
Accessing array elements are similar to accessing list or some other indexable datatype elements.

In [27]:
a_1d = np.array( [1,2,3] )
print( a_1d[1] )

2


In [30]:
a_2d = np.array( [ [1,2,3], [4,5,6] ] )

print( a_2d[1][2] ) # 1st way of accessing elements in a multidimensional array.
print( a_2d[1,2] )  # 2nd way of accessing elements in a multidimensional array.

6
6


In [32]:
a_2d = np.array( [ [1,2,3], [4,5,6] ] )
print("Initial: \n", a_2d)
a_2d[1][2] = 600
print("Final: \n", a_2d)

Initial: 
 [[1 2 3]
 [4 5 6]]
Final: 
 [[  1   2   3]
 [  4   5 600]]


### Changing a complete 1D inner array

In [33]:
a_2d = np.array( [ [1,2,3], [4,5,6] ] )
print("Initial: \n", a_2d)
a_2d[1] = 100,2000,300
print("Final: \n", a_2d)

Initial: 
 [[1 2 3]
 [4 5 6]]
Final: 
 [[   1    2    3]
 [ 100 2000  300]]


### Viewing a single complete COLUMN in a 2D array:
------------------------------------------------------
- For this, slicing operator must be used.
- To access column, only the second way of accessing numpy array elements must be used, i.e., [i, j, k, ... ndim] -> comma separated index values inside single pair of square brackets.

In [35]:
a_2d = np.array( [ [1,2,3], [4,5,6] ] )

print( a_2d[::, 0] )

[1 4]


## 9. Selecting a submatrix of a larger matrix:
------------------------------------------------

In [37]:
list_3x5 = [
    [1,2,3,4,5],
    [10,20,30,40,50],
    [100,200,300,400,500]
]

a_2d = np.array( list_3x5 )
print(a_2d)

[[  1   2   3   4   5]
 [ 10  20  30  40  50]
 [100 200 300 400 500]]


In [38]:
# Lower right submatrix 2x3:
sub_mat = a_2d[ 1::, 2:: ]

print(sub_mat)

[[ 30  40  50]
 [300 400 500]]


In [39]:
# Lower left submatrix 2x3:
sub_mat2 = a_2d[ 1::, :3: ]

print( sub_mat2 )

[[ 10  20  30]
 [100 200 300]]


In [41]:
list_6x9 = [
    [ 1,  2,  3,  4,  5,  6,  7,  8,  9],
    [10, 20, 30, 40, 50, 60, 70, 80, 90],
    [11, 22, 33, 44, 55, 66, 77, 88, 99],
    [12, 22, 23, 24, 25, 26, 27, 28, 29],
    [15, 25, 35, 45, 55, 65, 75, 85, 95],
    [17, 27, 37, 47, 57, 67, 77, 87, 97]
]

a_2d_large = np.array( list_6x9 )
print( a_2d_large )

[[ 1  2  3  4  5  6  7  8  9]
 [10 20 30 40 50 60 70 80 90]
 [11 22 33 44 55 66 77 88 99]
 [12 22 23 24 25 26 27 28 29]
 [15 25 35 45 55 65 75 85 95]
 [17 27 37 47 57 67 77 87 97]]


In [44]:
print( "Dimensions =", a_2d_large.ndim, "| Order =", a_2d_large.shape )

Dimensions = 2 | Order = (6, 9)


In [46]:
# sub_mat = a_2d_large[ ::2, ::2 ]
sub_mat = a_2d_large[ 0:4 , 0:4 ]

print( sub_mat )

[[ 1  2  3  4]
 [10 20 30 40]
 [11 22 33 44]
 [12 22 23 24]]


In [48]:
# Select the column in which all the elements are divisible by 5

print( a_2d_large[ :-1:, 4 ] )

[ 5 50 55 25 55]


## 10. Special value - numpy.nan:-
--------------------------------------
- In numpy, to fill a specific place with blank space, we place a special value there, which is `numpy.nan`
- `numpy.nan` is not a value as such, and it denotes absence of any values.
- `numpy.nan` evaluates to be False as a value. It is equivalent to `None` in Python, and `null` in other programming languages.
- `numpy.nan` is a `float` type value, and thus **can be stored in an array whose datatype contains float values.**

In [52]:
a = np.array( [ [1,2,3], [11,22,33] ], dtype=np.float32 )
print( a , end="\n\n")

a[1][1] = np.nan
print( a )

[[ 1.  2.  3.]
 [11. 22. 33.]]

[[ 1.  2.  3.]
 [11. nan 33.]]


## 11. Creating an array of zeros - `numpy.zeros()`:
------------------------------------------------------
- `np.zeros()` return a Numpy array whose all the elements are 0.
- **By default**, datatype of all elements will be `float`.
- Takes integer / tuple as a parameter, which is the shape of the resulting array that we want. Ex:-
    - np.zeros( (2,3) ) will give an array with all the values as 0, with 2 rows and 3 columns.

In [53]:
a0 = np.zeros(4)

print(a0, a0.dtype)

[0. 0. 0. 0.] float64


In [55]:
a0 = np.zeros( (4,2) )

print(a0, a0.dtype)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]] float64


## 12. Creating an array of ones - `numpy.ones()`:
------------------------------------------------------
- `np.ones()` return a Numpy array whose all the elements are 1.
- **By default**, datatype of all elements will be `float64`.
- Takes integer / tuple as a parameter, which is the shape of the resulting array that we want. Ex:-
    - np.ones( (2,3) ) will give an array with all the values as 1, with 2 rows and 3 columns.

In [57]:
a1 = np.ones(4)

print(a1, a1.dtype ) 

[1. 1. 1. 1.] float64


In [58]:
a1 = np.ones( (5,6) )

print(a1)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


## 13. Creating an array will all elements of same value - `numpy.full()`:
-----------------------------------------------------------------------------
- `np.full()` return a Numpy array whose all the elements are same.
- Syntax : `numpy.full( <shape_of_array> , <element> )`
- **By default**, datatype of all elements will be `int32`.
- Takes integer / tuple as 1st parameter, which is the shape of the resulting array that we want. 2nd parameter will be the value of each element, which must be an integer or decimal number. Ex:-
    - np.full( (2,3), 25 ) will give an array with all the values as 25, with 2 rows and 3 columns.

In [60]:
ax = np.full( 7, 10 )

print( ax, ax.dtype )

[10 10 10 10 10 10 10] int32


In [59]:
ax = np.full( (2,3), 25 )

print( ax )

[[25 25 25]
 [25 25 25]]


## 14. Creating IDENTITY MATRIX - `numpy.identity()`:
---------------------------------------------------------
- Syntax : `numpy.identity( <num_rows/columns> , dtype )`
- Takes 1st parameter as an integer, and always returns a square matrix (2D array with same rows and columns) with that many rows/columns.
- **By default**, datatype of all elements will be `float64`.
- <u><b>Identity Matrix</b>: A square matrix, whose all the elements along the principal diagonal is 1, rest all elements will be 0.</u>

In [61]:
ai = np.identity( 3 )

print(ai, ai.dtype)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] float64


In [62]:
ai = np.identity(5, dtype=np.int32)
print(ai)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


## 15. Creating an array of random values: `np.random.rand()` :
----------------------------------------------------------------
- Syntax : `np.random.rand( <num_elements_of_axis_n> , <num_elements_of_axis_(n-1)> , ... , <num_elements_of_axis_1> , <num_elements_of_axis_0> )`
- Gives an array whose all elements are floating numbers betweenn 0 and 1.
- Takes shape of array returned, in the parameter.
- Single or multiple parameters may be passed, where each parameter must be a positive integer. **Parameter should not be a tuple.**
- Number of parameters is equal to the number of dimensions of the resulting array.

In [66]:
ar = np.random.rand( 3 )
print(ar)

[0.75599274 0.33329211 0.52791195]


In [68]:
ar2 = np.random.rand( 3,5 )
print(ar2)

[[0.21398004 0.48365576 0.79672058 0.39409205 0.81284433]
 [0.52642404 0.59932113 0.4812573  0.54789801 0.49904331]
 [0.41106292 0.45514037 0.84751252 0.64492541 0.64734516]]


In [75]:
ar3 = np.random.rand(2,3,5)
print(ar3)

[[[0.30651528 0.98099589 0.8447457  0.72829167 0.40398309]
  [0.03304626 0.84495743 0.0297162  0.08106454 0.59216787]
  [0.48892606 0.9133818  0.50288565 0.87555131 0.10013466]]

 [[0.67239242 0.75142715 0.78033489 0.81189656 0.47157742]
  [0.23890869 0.22008003 0.26632612 0.2603216  0.45377677]
  [0.98877151 0.84649747 0.23254446 0.13977192 0.827909  ]]]


## 16. Creating an array of random values: 
## `np.random.randint( <min_int>=0(default) , <max_int> , size = <tuple_denoting_array_shape> )`
-----------------------------------------------------------------------------------------------------------------------
- Returns a numpy array with all the elements being integer.
- <b> If only 1 positive integer is passed as parameter, all the integer will be between 0 and `max_int`(1st parameter), with the `max_int` not included.</b>
    - Ex- `np.random.randint(8, size=(3,4))` : Give a (3,4) array, where all elements are between 0 to 8, 8 is excluded.
<b> If 2 positive integers are passed as parameter, all the integer will be between `min_int`(1st parameter) and `max_int`(2nd parameter), with the `max_int` not included.</b>
    - Ex- `np.random.randint(10, 15, size=(3,4))` : Give a (3,4) array, where all elements are between 10 to 15, 8 is excluded.

In [78]:
ar = np.random.randint(8, size=(5,4))
print(ar)

[[7 4 4 0]
 [2 4 3 0]
 [4 6 5 1]
 [1 7 3 6]
 [0 2 7 6]]


In [80]:
ar = np.random.randint( 10, 15, size=(5,6) )
print(ar)

[[14 12 10 14 13 12]
 [14 11 13 12 14 13]
 [10 10 10 12 13 11]
 [12 14 14 13 14 12]
 [12 13 12 14 12 11]]


<h1><center>More Properties and Operations</center></h1>
<hr><hr>

## 1. Getting total number of elements:-
-----------------------------------------

In [81]:
a = np.array([[1,2,3],[4,5,6]])
print(a.size)

6


## 2. Arithmetic mean - `mean()` or `average()`:-
- Arithmetic Mean is defined as (Sum of all elements of an array) / (Number of elements)

In [111]:
a = np.array([[1,2,3],[4,5,6]])

print( a.mean() )
print( np.mean(a) )

3.5
3.5


In [113]:
a = np.array([[1,2,3],[4,5,6]])

# print( a.average() )
print( np.average(a) )

3.5


In [83]:
print("1. ", a.mean() )
print("2. ", a.sum()/a.size)

1.  3.5
2.  3.5


## 3. Getting Principal Diagonal Elements - `diagonal()`:-
- <b>Principal Diagonal :</b> The diagonal that starts from **Top-Left to Bottom-Right**.
- Applicable for non-square matrices as well.

In [87]:
l = [
    [ 1, 2, 3],
    [ 4, 5, 6],
    [ 7, 8, 9]
]

a = np.array(l)
print( a.diagonal() )

[1 5 9]


In [88]:
l = [
    [ 1, 2, 3, 4],
    [ 4, 5, 6, 5],
    [ 7, 8, 9, 6]
]

a = np.array(l)
print( a.diagonal() )

[1 5 9]


## 4. Getting Trace of a matrix: `trace()`:
- Trance of a matrix is the sum of its principal diagonal elements.

In [98]:
l = [
    [ 1, 2, 3],
    [ 4, 5, 6],
    [ 7, 8, 9]
]

a = np.array(l)
print( a.trace() )

15


In [99]:
print( a.trace(), a.diagonal().sum() )

15 15


## 5. Largest and Smallest values in entire array: `max()` and `min()`, or `np.min()` and `np.max()`:

In [89]:
l = [
    [ 1, 2, 3, 4],
    [ 4, 5, 6, 5],
    [ 7, 8, 9, 6]
]

a = np.array(l)

print(f"Max = {a.max()} | Min = {a.min()}")

Max = 9 | Min = 1


In [110]:
l = [
    [ 1, 2, 3, 4],
    [ 4, 5, 6, 5],
    [ 7, 8, 9, 6]
]

a = np.array(l)

print(f"Max = {np.max(a)} | Min = {np.min(a)}")

Max = 9 | Min = 1


## 6. Changing the shape of existing array: `reshape()`:
- For `reshape()` to be applicable, the number of elements in Initial and Reshaped arrays must be same, else error is thrown.
- Returns the reshaped array, and does not modifies the original array.

In [90]:
l = [
    [1,2,1,4],
    [2,4,6,8],
    [3,6,9,5]
]

a = np.array(l)

print(a, a.shape)

[[1 2 1 4]
 [2 4 6 8]
 [3 6 9 5]] (3, 4)


In [94]:
a2 = a.reshape((6,2))

print(a2, a2.shape)

[[1 2]
 [1 4]
 [2 4]
 [6 8]
 [3 6]
 [9 5]] (6, 2)


In [93]:
# This will throw an error
print( a.reshape((5,2)) )

ValueError: cannot reshape array of size 12 into shape (5,2)

## 7. Getting Transpose of a matrix: `transpose()`

In [95]:
l = [
    [1, 2, 1, 4, 5],
    [2, 4, 6, 8, 7],
    [3, 6, 9, 5, 2]
]

a = np.array(l)

In [97]:
a_trans = a.transpose()

print(a, a_trans, sep="\n===============\n")

[[1 2 1 4 5]
 [2 4 6 8 7]
 [3 6 9 5 2]]
[[1 2 3]
 [2 4 6]
 [1 6 9]
 [4 8 5]
 [5 7 2]]


## 8. MATRIX OPERATIONS:-

### 1. Addition:-

In [102]:
a1 = np.array([
    [1,2,3],
    [3,2,1],
    [9,2,4]
])

a2 = np.array([
    [4,1,9],
    [2,4,2],
    [1,0,8]
])

b = a1 + a2

print( b )

[[ 5  3 12]
 [ 5  6  3]
 [10  2 12]]


### 2. Subtraction:-

In [103]:
a1 = np.array([
    [1,2,3],
    [3,2,1],
    [9,2,4]
])

a2 = np.array([
    [4,1,9],
    [2,4,2],
    [1,0,8]
])

b = a1 - a2

print( b )

[[-3  1 -6]
 [ 1 -2 -1]
 [ 8  2 -4]]


### 3. Corresponding element multiplication:-

In [104]:
a1 = np.array([
    [1,2,3],
    [3,2,1],
    [9,2,4]
])

a2 = np.array([
    [4,1,9],
    [2,4,2],
    [1,0,8]
])

b = a1 * a2

print( b )

[[ 4  2 27]
 [ 6  8  2]
 [ 9  0 32]]


### 4. Corresponding element division:-
- In this case, the matrix as denominator should have no element as 0.

In [106]:
a1 = np.array([
    [1,2,3],
    [3,2,1],
    [9,2,4]
])

a2 = np.array([
    [4,1,9],
    [2,4,2],
    [1,10,8]
])

b = a1 / a2

print( b )

[[0.25       2.         0.33333333]
 [1.5        0.5        0.5       ]
 [9.         0.2        0.5       ]]


### 5. Adding, Subtracting, Multiplying, Dividing constant from each array element:

In [107]:
a1 = np.array([
    [1,2,3],
    [3,2,1],
    [9,2,4]
])

print(
    a1 + 5,
    a1 - 6,
    a1 * 10,
    a1 / 2,
    a1 // 2,
    sep = "\n=========================\n"
)

[[ 6  7  8]
 [ 8  7  6]
 [14  7  9]]
[[-5 -4 -3]
 [-3 -4 -5]
 [ 3 -4 -2]]
[[10 20 30]
 [30 20 10]
 [90 20 40]]
[[0.5 1.  1.5]
 [1.5 1.  0.5]
 [4.5 1.  2. ]]
[[0 1 1]
 [1 1 0]
 [4 1 2]]


## 6. Performing MATRIX MULTIPLICATION - `numpy.matmul( <array1> , <array2> )`:

In [108]:
a1 = np.array([
    [1,2,3],
    [3,2,1],
    [9,2,4]
])

a2 = np.array([
    [4,1,9],
    [2,4,2],
    [1,10,8]
])

result = np.matmul( a1, a2 )
print( result )

[[ 11  39  37]
 [ 17  21  39]
 [ 44  57 117]]


## 7. DETERMINANT of a SQUARE MATRIX - `numpy.linalg.det( <matrix )`:

In [109]:
a1 = np.array([
    [1,2,3],
    [3,2,1],
    [9,2,4]
])

det_a1 = np.linalg.det( a1 )
print( det_a1 )

-36.000000000000014


## 8. Standard Deviation of all the elements of an array: `np.std( <array> )`
<hr><br><br>
<img src="./images/variance_stddev.jpg">

In [114]:
a1 = np.array([
    [1,2,3],
    [3,2,1],
    [9,2,4]
])

std_dev = np.std( a1 )
print(std_dev)

2.309401076758503


## 9. Variance of all the elements of an array: `np.var( <array> )`
- Variance = (Standard Deviation) ** 2

In [115]:
a1 = np.array([
    [1,2,3],
    [3,2,1],
    [9,2,4]
])

var = np.var( a1 )
print(var)

5.333333333333333


## 10. Generating array from values in a text file:
## `numpy.genfromtxt( <file_path> , delimiter = "<character_sequence>" )`:
- By default, datatype of elements will be `float64`

In [116]:
arr = np.genfromtxt( "./data/01_numbers.txt", delimiter=',' )
print( arr )

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [117]:
arr.dtype

dtype('float64')